### ISSUE TITLE
can't run

### ISSUE THREAD

**Issue by skyvider** [Youssef-Lehmam/OFPPTLANGUES-BOT#1]
py main.py
Traceback (most recent call last):
  File "C:\Users\yassi\Desktop\dist\main.py", line 2, in <module>
    from pyarmor_runtime_000000 import __pyarmor__
  File "C:\Users\yassi\Desktop\dist\pyarmor_runtime_000000\__init__.py", line 2, in <module>
    from .pyarmor_runtime import __pyarmor__
ImportError: DLL load failed while importing pyarmor_runtime: The specified module could not be found.

**Comment by Youssef-Lehmam** [comment]
Check now
